language: go
go:
  - 1.6
  - 1.7
  - master
notificaitons:
  email:
    recipients:
      gomatic@nicerobot.org
    on_success: change
    on_failure: always
install:
  - go get -t ./...
script:
  - go test -v
